name: pdf_flutter
description: Displaying PDF from Network, File and assets easily like we display
  Image in Flutter Widget.
version: 2.0.0
homepage: https://github.com/erluxman/pdf_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  custom_path_provider:
    path: ./custom_path_provider
  custom_flutter_cache_manager:
    path: ./custom_flutter_cache_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.erluxman.pdf_flutter
        pluginClass: PdfFlutterPlugin
      ios:
        pluginClass: PdfFlutterPlugin
